function [y1] = myNeuralNetworkFunctionjeden(x1)
%MYNEURALNETWORKFUNCTIONJEDEN neural network simulation function.
%
% Auto-generated by MATLAB, 04-Apr-2022 12:12:37.
% 
% [y1] = myNeuralNetworkFunctionjeden(x1) takes these arguments:
%   x = 2xQ matrix, input #1
% and returns:
%   y = 4xQ matrix, output #1
% where Q is the number of samples.

%#ok<*RPMT0>

% ===== NEURAL NETWORK CONSTANTS =====

% Input 1
x1_step1.xoffset = [-7.9545730512395;-4.95191490490469];
x1_step1.gain = [0.119942601503472;0.183458332593331];
x1_step1.ymin = -1;

% Layer 1
b1 = [-2.3762711820640936011;-1.6354064601362297005;0.8671899389753735532];
IW1_1 = [5.4306987887415285599 -6.1929087842920180762;-5.4812559634668414077 -2.0174980352278306661;2.0830175489271294254 -2.8332284760679935509];

% Layer 2
b2 = [2.0459915062043232403;0.95388896948109069829;-2.6352488421241386796;-2.0962796115191877355];
LW2_1 = [-8.218134576276783676 -5.9896591001441352731 2.0618248740095066474;-2.4532468531330384742 5.1469267705624925924 -8.8371381256004966076;6.2898185971106181924 -10.448794911030887533 1.8344661166953750708;3.4447738990241969503 9.3413488936552866448 4.8456894241856440786];

% ===== SIMULATION ========

% Dimensions
Q = size(x1,2); % samples

% Input 1
xp1 = mapminmax_apply(x1,x1_step1);

% Layer 1
a1 = tansig_apply(repmat(b1,1,Q) + IW1_1*xp1);

% Layer 2
a2 = softmax_apply(repmat(b2,1,Q) + LW2_1*a1);

% Output 1
y1 = a2;
end

% ===== MODULE FUNCTIONS ========

% Map Minimum and Maximum Input Processing Function
function y = mapminmax_apply(x,settings)
  y = bsxfun(@minus,x,settings.xoffset);
  y = bsxfun(@times,y,settings.gain);
  y = bsxfun(@plus,y,settings.ymin);
end

% Competitive Soft Transfer Function
function a = softmax_apply(n,~)
  if isa(n,'gpuArray')
    a = iSoftmaxApplyGPU(n);
  else
    a = iSoftmaxApplyCPU(n);
  end
end
function a = iSoftmaxApplyCPU(n)
  nmax = max(n,[],1);
  n = bsxfun(@minus,n,nmax);
  numerator = exp(n);
  denominator = sum(numerator,1); 
  denominator(denominator == 0) = 1;
  a = bsxfun(@rdivide,numerator,denominator);
end
function a = iSoftmaxApplyGPU(n)
  nmax = max(n,[],1);
  numerator = arrayfun(@iSoftmaxApplyGPUHelper1,n,nmax);
  denominator = sum(numerator,1);
  a = arrayfun(@iSoftmaxApplyGPUHelper2,numerator,denominator);
end
function numerator = iSoftmaxApplyGPUHelper1(n,nmax)
  numerator = exp(n - nmax);
end
function a = iSoftmaxApplyGPUHelper2(numerator,denominator)
  if (denominator == 0)
    a = numerator;
  else
    a = numerator ./ denominator;
  end
end

% Sigmoid Symmetric Transfer Function
function a = tansig_apply(n,~)
  a = 2 ./ (1 + exp(-2*n)) - 1;
end
