function [y1] = myNeuralNetworkFunctioncluster(x1)
%MYNEURALNETWORKFUNCTIONCLUSTER neural network simulation function.
%
% Auto-generated by MATLAB, 14-Apr-2022 12:09:59.
% 
% [y1] = myNeuralNetworkFunctioncluster(x1) takes these arguments:
%   x = 2xQ matrix, input #1
% and returns:
%   y = 4xQ matrix, output #1
% where Q is the number of samples.

%#ok<*RPMT0>

% ===== NEURAL NETWORK CONSTANTS =====

% Layer 1
IW1_1 = [9.0737496481035329055 3.3034164377282340119;1.8708531965501880023 -3.7126887806573471984;8.232847809129639316 -2.2623523176804187784;-4.8343653538747526355 -0.7864695774034360376];

% ===== SIMULATION ========

% Input 1
% no processing

% Layer 1
z1 = negdist_apply(IW1_1,x1);
a1 = compet_apply(z1);

% Output 1
y1 = a1;
end

% ===== MODULE FUNCTIONS ========

% Negative Distance Weight Function
function z = negdist_apply(w,p,~)
  [S,R] = size(w);
  Q = size(p,2);
  if isa(w,'gpuArray')
    z = iNegDistApplyGPU(w,p,R,S,Q);
  else
    z = iNegDistApplyCPU(w,p,S,Q);
  end
end
function z = iNegDistApplyCPU(w,p,S,Q)
  z = zeros(S,Q);
  if (Q<S)
    pt = p';
    for q=1:Q
      z(:,q) = sum(bsxfun(@minus,w,pt(q,:)).^2,2);
    end
  else
    wt = w';
    for i=1:S
      z(i,:) = sum(bsxfun(@minus,wt(:,i),p).^2,1);
    end
  end
  z = -sqrt(z);
end
function z = iNegDistApplyGPU(w,p,R,S,Q)
  p = reshape(p,1,R,Q);
  sd = arrayfun(@iNegDistApplyGPUHelper,w,p);
  z = -sqrt(reshape(sum(sd,2),S,Q));
end
function sd = iNegDistApplyGPUHelper(w,p)
  sd = (w-p) .^ 2;
end

% Competitive Transfer Function
function a = compet_apply(n,~)
  if isempty(n)
    a = n;
  else
    [S,Q] = size(n);
    nanInd = any(isnan(n),1);
    a = zeros(S,Q,'like',n);
    [~,maxRows] = max(n,[],1);
    onesInd = maxRows + S*(0:(Q-1));
    a(onesInd) = 1;
    a(:,nanInd) = NaN;
  end
end
