function [y1] = myNeuralNetworkFunctionjeden(x1)
%MYNEURALNETWORKFUNCTIONJEDEN neural network simulation function.
%
% Auto-generated by MATLAB, 14-Apr-2022 12:03:44.
% 
% [y1] = myNeuralNetworkFunctionjeden(x1) takes these arguments:
%   x = 2xQ matrix, input #1
% and returns:
%   y = 4xQ matrix, output #1
% where Q is the number of samples.

%#ok<*RPMT0>

% ===== NEURAL NETWORK CONSTANTS =====

% Input 1
x1_step1.xoffset = [-6.24480677247567;-4.95123635620204];
x1_step1.gain = [0.121466583462424;0.197376671579521];
x1_step1.ymin = -1;

% Layer 1
b1 = [1.801807348786233165;0.48246456777338897481;1.3851415745155570836];
IW1_1 = [-2.7489815064442200132 5.7395169824441776285;-5.1263242429176720805 -2.198758523757154304;3.4276608335400062799 0.89949591254648841865];

% Layer 2
b2 = [-0.19180121659849719284;0.44697249092026380968;-0.99263097882965101171;0.16967566183288645965];
LW2_1 = [6.3875914594979699146 -5.545263835869494784 0.93753729290035114907;5.6666136736794827655 4.8813389585390023484 -2.9957453237763211895;-6.3829756920341145232 -6.080234464681490536 1.3645661504973434219;-4.9479893856494330251 6.7983746857023374943 1.44420922298625376];

% ===== SIMULATION ========

% Dimensions
Q = size(x1,2); % samples

% Input 1
xp1 = mapminmax_apply(x1,x1_step1);

% Layer 1
a1 = tansig_apply(repmat(b1,1,Q) + IW1_1*xp1);

% Layer 2
a2 = softmax_apply(repmat(b2,1,Q) + LW2_1*a1);

% Output 1
y1 = a2;
end

% ===== MODULE FUNCTIONS ========

% Map Minimum and Maximum Input Processing Function
function y = mapminmax_apply(x,settings)
  y = bsxfun(@minus,x,settings.xoffset);
  y = bsxfun(@times,y,settings.gain);
  y = bsxfun(@plus,y,settings.ymin);
end

% Competitive Soft Transfer Function
function a = softmax_apply(n,~)
  if isa(n,'gpuArray')
    a = iSoftmaxApplyGPU(n);
  else
    a = iSoftmaxApplyCPU(n);
  end
end
function a = iSoftmaxApplyCPU(n)
  nmax = max(n,[],1);
  n = bsxfun(@minus,n,nmax);
  numerator = exp(n);
  denominator = sum(numerator,1); 
  denominator(denominator == 0) = 1;
  a = bsxfun(@rdivide,numerator,denominator);
end
function a = iSoftmaxApplyGPU(n)
  nmax = max(n,[],1);
  numerator = arrayfun(@iSoftmaxApplyGPUHelper1,n,nmax);
  denominator = sum(numerator,1);
  a = arrayfun(@iSoftmaxApplyGPUHelper2,numerator,denominator);
end
function numerator = iSoftmaxApplyGPUHelper1(n,nmax)
  numerator = exp(n - nmax);
end
function a = iSoftmaxApplyGPUHelper2(numerator,denominator)
  if (denominator == 0)
    a = numerator;
  else
    a = numerator ./ denominator;
  end
end

% Sigmoid Symmetric Transfer Function
function a = tansig_apply(n,~)
  a = 2 ./ (1 + exp(-2*n)) - 1;
end
